#!/bin/sh

# colourize tty output
C1=""
C2=""
if [ -t 1 ]; then
    C1="\033[32m"
    C2="\033[0m"
fi

if [ -z "$1" ]; then
    echo "No date specified; showing range of 1 week."
    find . -type f -newermt "$(date --rfc-3339=date -d "1 week ago")" -printf "$C1%T+$C2\t%p\n" | sort
elif [ "$1" = "-h" ]; then
    echo "Specify a date range in the format 'yyyy-mm-dd'."
elif [ "$1" = "-e" ] && [ -n "$2" ]; then
    echo "No date specified; showing range of 1 week."
    find . -type f -newermt "$(date --rfc-3339=date -d "1 week ago")" -printf "$C1%T+$C2\t%p\n" -exec sh -c "$2" \;
elif [ "$2" = "-e" ] && [ -n "$3" ]; then
    find . -type f -newermt "$1" -printf "$C1%T+$C2\t%p\n" -exec sh -c "$3" \;
elif [ -z "$2" ]; then
    find . -type f -newermt "$1" -printf "$C1%T+$C2\t%p\n" | sort
elif [ "$3" = "-e" ] && [ -n "$4" ]; then
    find . -type f -newermt "$1" ! -newermt "$2" -printf "$C1%T+$C2\t%p\n" -exec sh -c "$4" \;
else
    find . -type f -newermt "$1" ! -newermt "$2" -printf "$C1%T+$C2\t%p\n" | sort
fi
