#!/bin/sh

if [ -z "$1" ]; then
    find . -name ".git" -prune -o -not -empty -type f -exec md5sum {} + | sort | uniq -w32 -dD
else
    find . -name ".git" -prune -o -not -empty -type f -iname "$1" -exec md5sum {} + | sort | uniq -w32 -dD
fi
