#!/usr/bin/env python3
"""
View any image in the terminal.
Required python package 'term-image'.
"""

from term_image.image import from_file
import argparse


parser = argparse.ArgumentParser(prog="Terminal Image Viewer",
                                 description="View any image in the terminal.")
parser.add_argument("file", type=str,
                    help="Path to the file you want to display.")
args = parser.parse_args()

image = from_file(args.file)
print(image)
